### ISSUE TITLE
Consider dropping use of extra_path in distutils scripts

### ISSUE THREAD

**Issue by jaraco** [mattneub/appscript#14]
In the Python scripts for this project, I find `extra_path = "aeosa"`, which according to [Python #27919](http://bugs.python.org/issue27919) is deprecated.

If this feature is something on which you rely heavily, please feel free to post back to the Python ticket explaining your use case and why you think this feature should be retained.

Thanks.

**Comment by mattneub** [comment]
Hey, it's not my code. If it's something you know how to fix without breaking AppScript, submit a pull request, or fork it and make it better. Otherwise, lay off. Thanks.
