### ISSUE TITLE
rb-appscript under 10.12 (Sierra)?

### ISSUE THREAD

**Issue by Stray** [mattneub/appscript#16]
Hi, thanks for keeping this alive.

I have a legacy project that depends on project sprouts, which depends on rb-appscript.

Whether I install it as a gem, or `make` manually, I get the same errors:
[gem_make_out.txt](https://github.com/mattneub/appscript/files/763854/gem_make_out.txt)

Has anyone had success with rb-appscript in 10.12? The last version I installed it under was 10.8.

Thanks,

Stray

**Comment by mattneub** [comment]
It seems likely that you've upgraded the same machine from system to system and thus have old versions of tools/libraries. I just tried installing rb-appscript in a completely clean install of Sierra and it worked. Here's what I did.

* Installed the latest Xcode beta (currently Version 8.3 beta 4 (8W143q)) and, in its Preferences, set the Locations command line tools pop-up to point to it.

* Installed the corresponding command-line tools from http://adcdownload.apple.com/Developer_Tools/Command_Line_Tools_macOS_10.12_for_Xcode_8.3_beta_4/Command_Line_Tools_macOS_10.12_for_Xcode_8.3_beta_4.dmg

* `cd` into `trunk` and say `ruby extconf.rb`, then `make`, then `sudo make install`.

Here's a screen shot of a ruby script using rb-appscript to target iTunes (run in TextMate):

![screen shot 2017-03-12 at 8 04 26 am](https://cloud.githubusercontent.com/assets/838939/23832883/dd6b1940-06fa-11e7-996d-63791aa19c3d.png)
