### ISSUE TITLE
objc-appscript will not build for 10.6 or later

### ISSUE THREAD

**Issue by abarnert** [mattneub/appscript#3]
objc-appscript comes with 6 separate build configurations, each of which hardcodes either 10.4u or 10.5 SDK. Plus, the 10.4 ones require gcc 4.0, and both specify ppc architectures.

This means you can't build with recent versions of Xcode; as of 4.5, the oldest SDK you can use is 10.7, there's no gcc 4.0, and no ppc or ppc64 compiler.

Fixing this locally isn't too hard if you know what you're doing. Here's how to do it in the Xcode 4 GUI:
- In the project Info, delete the 10.4 configs, and rename the 10.5 configs to remove the "10.5" from the names.
- Switch to build settings, change Architectures for just the two Release configs to Standard (or whatever ${ARCHS_STANDARD_32_64_BIT} is called in your version of Xcode's GUI).
- Set the Base SDK for all three configs to Latest OS X.
- Set the OS X Deployment Target for all three configs to OS X 10.5.

This works at least back to Xcode 3.1.1 on a 10.5 i386 machine.

But of course it removes the ability to do 10.4 builds, and PPC builds, and it could break build scripts that people have written to wrap Appscript xcodebuild.

So, it might be better to leave the 10.4 and 10.5 configs alone, create 3 new "Latest" configs that are cloned from the 10.5 configs, then apply the changes above to the new configs only.

**Comment by mattneub** [comment]
Thanks for the instructions. I think a sensible approach at this point is to switch to [SwiftAutomation](https://bitbucket.org/hhas/swiftae). It is the natural descendent of objc-appscript and works in the current version of Xcode.
